server:
  port: 9090
keycloak:
  realm: development
  auth-server-url: http://localhost:9091
  ssl-required: external
  resource: keycloak-authentication-authorization
  credentials:
    secret: 0F6Tp5GEQ5BTkKB50ctBZ6of58MEJQjk
  security-constraints:
    - auth-roles:
        - ADMIN
      security-collections:
        - name: admin stuff
          patterns:
            - /v1/colors/*
          methods:
            - GET
            - DELETE
    - auth-roles:
        - USER
      security-collections:
        - name: user stuff
          patterns:
            - /v1/colors/*
          methods:
            - GET
            - POST